### ISSUE TITLE
Failed to install required dependencies

### ISSUE THREAD

**Issue by ligs01** [lassoan/SlicerMONAIAuto3DSeg#75]
Command '['D:/Slicer 5.7.0-2024-07-22/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'monai[fire,pyyaml,nibabel,pynrrd,psutil,tensorboard,skimage,itk,tqdm]>=1.3']' returned non-zero exit status 2.

details：
Traceback (most recent call last):
  File "D:\Slicer 5.7.0-2024-07-22\bin\Python\slicer\util.py", line 3295, in tryWithErrorDisplay
    yield
  File "D:/Slicer 5.7.0-2024-07-22/slicer.org/Extensions-32953/MONAIAuto3DSeg/lib/Slicer-5.7/qt-scripted-modules/MONAIAuto3DSeg.py", line 505, in onApply
    self.logic.setupPythonRequirements()
  File "D:/Slicer 5.7.0-2024-07-22/slicer.org/Extensions-32953/MONAIAuto3DSeg/lib/Slicer-5.7/qt-scripted-modules/MONAIAuto3DSeg.py", line 1076, in setupPythonRequirements
    slicer.util.pip_install(monaiInstallString)
  File "D:\Slicer 5.7.0-2024-07-22\bin\Python\slicer\util.py", line 3927, in pip_install
    _executePythonModule("pip", args)
  File "D:\Slicer 5.7.0-2024-07-22\bin\Python\slicer\util.py", line 3888, in _executePythonModule
    logProcessOutput(proc)
  File "D:\Slicer 5.7.0-2024-07-22\bin\Python\slicer\util.py", line 3854, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['D:/Slicer 5.7.0-2024-07-22/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'monai[fire,pyyaml,nibabel,pynrrd,psutil,tensorboard,skimage,itk,tqdm]>=1.3']' returned non-zero exit status 2.

**Comment by diazandr3s** [comment]
Hi @ligs01,

Could you please try with a clean Slicer Preview again and see if the problem persist?

**Comment by lassoan** [comment]
Thank you for the update, I'm closing this issue then.
